package assout

// defaultASSHeader is the generated header for SRT-to-ASS conversion.
// Font: Microsoft YaHei (user decision), Size: 58 (comparable to player default
// SRT rendering at ~5.4% of 1080p screen height), PlayRes: 1920x1080 (modern
// standard), CRLF line endings (ASS convention).
const defaultASSHeader = "[Script Info]\r\n" +
	"; Script generated by mkv-sub-extractor\r\n" +
	"ScriptType: v4.00+\r\n" +
	"PlayResX: 1920\r\n" +
	"PlayResY: 1080\r\n" +
	"WrapStyle: 0\r\n" +
	"ScaledBorderAndShadow: yes\r\n" +
	"\r\n" +
	"[V4+ Styles]\r\n" +
	"Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, " +
	"OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, " +
	"ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, " +
	"Alignment, MarginL, MarginR, MarginV, Encoding\r\n" +
	"Style: Default,Microsoft YaHei,58," +
	"&H00FFFFFF,&H000000FF,&H00000000,&H80000000," +
	"0,0,0,0," +
	"100,100,0,0," +
	"1,2,1," +
	"2," +
	"20,20,30," +
	"1\r\n"

// defaultEventsFormat is the Format line for the [Events] section.
const defaultEventsFormat = "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\r\n"
